### ISSUE TITLE
Modbus Master ESP32

### ISSUE THREAD

**Issue by luisgcu** [JhonControl/Arduino_Modbus_Master_in_5_minutes#1]
Hello,
Thanks very much for all your tutorials.  
Just wondering what need to be done  to compile your sample code for ESP32 ?
I got the following error:
ModbusRtu.h:740:7: error: 'UCSR0A' was not declared in this scope
       UCSR0A=UCSR0A |(1 << TXC0);

this is the port  config that  I am using on the ESP32:
HardwareSerial Serial2(2);
Modbus master(0,2,3);
By the way I am getting the same issue on arduino Leonardo.
your help would be appreciated.
Saludos

**Comment by JhonControl** [comment]
Hello @luisgcu , Initially, thank you for implementing these tests in your applications.
The error concerning:
ModbusRtu.h: 740: 7: error: 'UCSR0A' was not declared in this scope
UCSR0A = UCSR0A | (1 << TXC0);

They are the direct instructions and registers for serial communication UART,
unfortunately these instructions are **exclusive to AVR** in a few words will **only work in atmega or Arduino's,** should work in your arduino leonardo.
In the case of ESP32 it is incompatible by directives in serial libraries, I will perform tests later.

Some time ago I did some tests with other libraries in my other site [**TrialCommand**](http://en.trialcommand.com) , although I did not upload anything again, you could try this.
There are 2 tutorials although they are similar has differences:
For **ESP8266**: [ESP8266 master modbus rtu rs232](http://en.trialcommand.com/blog/esp8266-master-modbus-rtu-rs232/
)
For **Arduino** : [Arduino master modbus rtu rs232](http://en.trialcommand.com/blog/arduino-master-modbus-rtu-rs232/)
in the case of ESP32, it is not available yet, I have not tested if it compiles, I have thought to carry out tests ... I will resume them in [PDAControl](http://pdacontrolen.com)
the source of the previous examples are this article, there are explained in detail the modifications in the libraries: [Tutorial ESP8266 12E Modbus RTU Master (Improved)](http://pdacontrolen.com/tutorial-esp8266-12e-modbus-rtu-master/
)
Regards

**Comment by luisgcu** [comment]
Hello @JhonControl  thanks for taking the time to respond.
I tried a year ago with the ESP8266 using the software serial for the modbus connection, leaving the hardware serial for debug. But  I got a problem that I see other have same to.. if Disconnect the  serial connection to the modbus device the ESP8266 crash . So at that time I gave up with ESP8266 and did my test with Particle Photon that have  a hardware serial connection available  for RS485 while I can do debug by USB serial or the particle cloud. This was the library that I used : [https://github.com/pkourany/ModBusMaster](url) wich ported to work with Particle Photon from this library [https://github.com/4-20ma/ModbusMaster](url) .  That last library did compile for Esp32 but it didn't read anything, and the thing is the port is working.. I can see data going out the esp32  serial port on GPIO16-17.. but look like data command send is corrupted or out of sync.. 
This Library  [https://github.com/angeloc/simplemodbusng/tree/master/SimpleModbusMaster ](url)  SimpleModbusmaster.. compile for  the ESP32  and it works I was able to read some holding register, but I think it lack of features or I maybe cant understand how it works.. I believe you use that in your website.

The last Library for modbus that I found look pretty interesting..   [https://github.com/EnviroDIY/SensorModbusMaster](url) it works  I tested in arduino Mega and Leonardo.  it compile for the ESp32 but I can't get any response from the modbus slave. 
That library have a lot functions to convert the buffer to different data types, I want that to be able to read 32 bit register from slave. I still trying to figure out how to do that, the slave that I am connection have single registers that holds a 32 bit parameter. 
I am also working to see if i can develop a modbus TCP master using ESP32 but not by the WIFI connection, instead I want the ESP32 to have hardwired Ethernet to the slave ( some industrial PLC  have ethernet ports  and Not RS485 ) we may use a hardware like this: [https://www.olimex.com/Products/IoT/ESP32-GATEWAY/open-source-hardware](url) I want the WIFI to get connected to the internet to IOT services. 

regards

**Comment by JhonControl** [comment]
Hello @luisgcu , Thanks for comprating your tests and the libraries are very interesting, I will take some time to test them, a while ago I found this library created by:[**yaacov**](https://github.com/yaacov)
I was trying the Modbus TCP Slave version for ESP8266 works very well, I'm doing some optimizations to understand its operation, later upload the results.
[**ArduinoModbusSlaveTCP**](https://github.com/yaacov/ArduinoModbusSlaveTCP)
Maybe you're interested in Modbus RTU versions although I think they are slaves, although I have not tried them.
[**ArduinoModbusESP**](https://github.com/yaacov/ArduinoModbusESP)
It is quite interesting your project with ESP32, I would recommend using it **esp-idf**, although it seems complex, it is very complete, It is more efficient than Arduino IDE.
regards
